# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
# Authorization: Token ecd8f61efb2a2c5835e71191c3be369fda6c861c

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ecd8f61efb2a2c5835e71191c3be369fda6c861c

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# удалить объявление
DELETE {{baseUrl}}/advertisements/10/
Authorization: Token 87d49649d968b3f63cc0ee7d540d45960abe7e2a

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/8/
Content-Type: application/json
Authorization: Token 87d49649d968b3f63cc0ee7d540d45960abe7e2a

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-09-08
Content-Type: application/json
